### PR TITLE
Fixed old DFU serial number for STLINK programmers

### LINKED ISSUE #417: STLINK/V2-1 and STLINK/V2 SN incompatibility on NUCLEO-F401RE board
- [X] Programmer/board type: NUCLEO-F401RE
- [X] Programmer firmware version: n/a
- [X] Operating system: Mac OS X
- [X] Stlink tools version and/or git commit hash: https://github.com/texane/stlink/commit/0f6dcbdf218ead70ce6f1322ae55db1fb73d4b79 (> v1.2.0)
- [X] Stlink commandline tool name: `st-util` 
- [X] Target chip (and optional board): e.g STM32F401RE (NUCLEO-F401RE)

Output:

```
$ system_profiler SPUSBDataType
        STM32 STLink:

          Product ID: 0x374b
          Vendor ID: 0x0483  (STMicroelectronics)
          Version: 1.00
          Serial Number: 0672FF494951785087023310
          Speed: Up to 12 Mb/sec
          Manufacturer: STMicroelectronics
$ ./st-info --probe
Found 1 stlink programmers
 serial: 303637324646343934393531373835
openocd: "\x30\x36\x37\x32\x46\x46\x34\x39\x34\x39\x35\x31\x37\x38\x35"
  flash: 524288 (pagesize: 16384)
   sram: 98304
 chipid: 0x0433
  descr: F4 device (Dynamic Efficency)
```

The current stlink tools/library is unable to detect a binary or hexstring serial number. The best fix is to detect if the serial is already hex encoded or encode it into a hex string. We need to have a generic `hexstr_from_bin`, `hexstr_to_bin` and `hexstr_is_valid`.

### PR DESCRIPTION
**Pull request by tarek-bochkati**
Signed-off-by: Tarek BOCHKATI <tarek.bouchkati@gmail.com>

(Closes #417, #494)

### CODE REVIEW

File: src/stlink-lib/usb.c [hunk 1]
```diff
@@ -1159,6 +1159,40 @@ static stlink_backend_t _stlink_usb_backend = {
...
+		sizeof(desc_serial));
+
+	if (ret < 0) return ret; // could not read serial
+
+	unsigned char len = desc_serial[0];
+
+	if (len == ((STLINK_SERIAL_MAX_SIZE + 1) * 2)) { /* len == 50 */
+		/* good ST-Link adapter */
+		ret = libusb_get_string_descriptor_ascii(
+			handle, desc->iSerialNumber, (unsigned char *)serial, STLINK_SERIAL_MAX_SIZE + 1);
```
Comment (Ant-ON) [inline src/stlink-lib/usb.c:1183]: I would add escaping `serial` in this case as well. Although it's easier to move line 1188 to line before `return 0` (line 1193). The serial number is displayed by printf and this can lead to unpredictable behavior.

File: src/stlink-lib/usb.c [hunk 2]
```diff
@@ -1236,15 +1270,12 @@ stlink_t *stlink_open_usb(enum ugly_loglevel verbose, int reset, char serial[STL
 
         if (ret) { continue; } // could not open device
 
-        sl->serial_size = libusb_get_string_descriptor_ascii(
-            handle, desc.iSerialNumber, (unsigned char *)sl->serial, sizeof(sl->serial));
+        ret = stlink_serial(handle, &desc, sl->serial);
 
         libusb_close(handle);
 
-        if (sl->serial_size < 0) { continue; } // could not read serial
```
Comment (Ant-ON) [inline src/stlink-lib/usb.c:1244]: It would be nice to keep the check of getting serial number ( `if (ret < 0)...` )

**Comment by Ant-ON** [comment]
For the work correctly of "--- serial" parameter is necessary to rewrite the parsing of the serial number. See:
https://github.com/stlink-org/stlink/blob/cc9bedd13fe79207508ad2cfd95d738ed2babdf0/src/st-util/gdb-server.c#L198-L207
https://github.com/stlink-org/stlink/blob/cc9bedd13fe79207508ad2cfd95d738ed2babdf0/src/st-flash/flash_opts.c#L111-L120

**Comment by Nightwalker-87** [comment]
There also is a build fail on macOS, but it looks as if this is related to the current CI config for macOS
I'll fix that soon, and we'll have a look at it again afterwards, so don't bother too much about it right now. :wink:

File: src/stlink-lib/usb.c (hunk 1 above)
Comment (tarek-bochkati) [reply src/stlink-lib/usb.c:1183]: not needed, read the manual
or dig in usb library
https://github.com/libusb/libusb/blob/eee6998395184d87bd8e9c07ce2637caed1207f4/libusb/descriptor.c#L1137

File: src/stlink-lib/usb.c (hunk 2 above)
Comment (tarek-bochkati) [reply src/stlink-lib/usb.c:1244]: well spotted

**Comment by tarek-bochkati** [comment]
> There also is a build fail on macOS, but it looks as if this is related to the current CI config for macOS
> I'll fix that soon, and we'll have a look at it again afterwards, so don't bother too much about it right now. 😉

I have seen the failure log, so I already ignored it ...

**Comment by tarek-bochkati** [comment]
> For the "--- serial" parameter work correctly is necessary to rewrite the parsing of the serial number.
shit! this should be handled in one place ...
I will check it tonight

File: src/stlink-lib/usb.c (hunk 1 above)
Comment (Ant-ON) [reply src/stlink-lib/usb.c:1183]: Thanks for the info! I have not found in the doxygen that the returned string is \0 terminated

**Comment by Nightwalker-87** [comment]
I've updated the Travis CI settings for macOS.
However there are still problems with the build on 10.14 and it still seems to be a lousy Xcode related issue. :vomiting_face:

**Comment by tarek-bochkati** [comment]
another Patch-Set is pushed, please let me know if this is OK.

**Comment by tarek-bochkati** [comment]
> I've updated the Travis CI settings for macOS.
> However there are still problems with the build on 10.14 and it still seems to be a lousy Xcode related issue. 🤮

still failing on macos :/

**Comment by Nightwalker-87** [comment]
Yeah, I'm still trying to solve it. It's not specifically related to this PR, but also other commits / PRs.

**Review by Nightwalker-87 — APPROVED** [review]

**Review by Ant-ON — APPROVED** [review]

**Comment by tarek-bochkati** [comment]
happy to see this approved and solved your issue.
and good luck with STM32U5 support 😨

**Comment by Nightwalker-87** [comment]
@tarek-bochkati: I'll merge this as soon as possible.
Thank you so much for contributing. May I add you to our list of project contributors?
Looking forward to stay in touch.

**Comment by tarek-bochkati** [comment]
> @tarek-bochkati: I'll merge this as soon as possible.
> Thank you so much for contributing. May I add you to our list of project contributors?
> Looking forward to stay in touch.

honestly I don't plan to be an active contributor in this project.
but I'm watching the evolution here and I can contribute time to time (my main focus is contributing to OpenOCD as part of my job)

**Comment by Nightwalker-87** [comment]
That's absolutely fine - there are no expectations associated with this.
For explanation: Our list of contributors is part of the project source code and aims to cover people who have brought notable improvements to the project pointing out the character of a community based project.

**Comment by tarek-bochkati** [comment]
Then we agree on this ;)
